steps:
  - name: gcr.io/cloud-builders/docker
    id: build-jupyter-singleuser-standard
    args:
      - build
      - --build-arg
      - BASE_IMAGE=${_BASE_IMAGE}
      - --build-arg
      - IMAGE_VERSION=${_IMAGE_TAG}
      - -t
      - ${_IMAGE_REPO}:${_IMAGE_TAG}
      - .

  - name: gcr.io/cloud-builders/docker
    id: push-jupyter-singleuser-standard
    args:
      - push
      - ${_IMAGE_REPO}:${_IMAGE_TAG}

images:
  - ${_IMAGE_REPO}:${_IMAGE_TAG}

substitutions:
  _BASE_IMAGE: asia-northeast3-docker.pkg.dev/prj-b-cicd-local-236d/ar-sandbox-platform/jupyterhub-k8s-singleuser-sample:4.2.0
  _IMAGE_REPO: asia-northeast3-docker.pkg.dev/prj-b-cicd-local-236d/ar-sandbox-platform/jupyterhub-k8s-singleuser-standard
  _IMAGE_TAG: 4.2.0-r1-test

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 1800s
